In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Global_Financial_Analysis/Global_Stock_Data.csv")
df

,Unnamed: 0.1,Unnamed: 0,Date,Close,High,Low,Open,Volume,Company,Country,Adj Close
0,0,0,2026-01-02,44.906544,44.906544,44.523818,44.680834,3035952.0,BHP,Australia,NaN
1,1,1,2026-01-05,45.613117,45.779949,45.053748,45.142070,5888054.0,BHP,Australia,NaN
2,2,2,2026-01-06,46.339317,46.481613,45.946776,46.437451,8048129.0,BHP,Australia,NaN
3,3,3,2026-01-07,46.810364,47.585631,46.525772,47.183278,7268819.0,BHP,Australia,NaN
4,4,4,2026-01-08,46.457077,46.888869,46.290246,46.692603,6359264.0,BHP,Australia,NaN
...,...,...,...,...,...,...,...,...,...,...,...
20931,2135,2135,2026-06-01,109.330002,113.300003,106.330002,109.430000,134900400.0,Intel,USA,NaN
20932,2136,2136,2026-06-02,107.930000,109.000000,104.169998,107.449997,106336200.0,Intel,USA,NaN
20933,2137,2137,2026-06-03,112.709999,118.290001,110.860001,116.419998,118928800.0,Intel,USA,NaN
20934,2138,2138,2026-06-04,111.779999,113.139999,107.480003,108.400002,77325800.0,Intel,USA,NaN
20935,2139,2139,2026-06-05,99.169998,106.480003,98.330002,106.480003,144388800.0,Intel,USA,NaN

In [5]:
df = df.drop('Unnamed: 0.1',axis=1)
df = df.drop(['Adj Close'],axis=1)
df

,Date,Close,High,Low,Open,Volume,Company,Country
0,2026-01-02,44.906544,44.906544,44.523818,44.680834,3035952.0,BHP,Australia
1,2026-01-05,45.613117,45.779949,45.053748,45.142070,5888054.0,BHP,Australia
2,2026-01-06,46.339317,46.481613,45.946776,46.437451,8048129.0,BHP,Australia
3,2026-01-07,46.810364,47.585631,46.525772,47.183278,7268819.0,BHP,Australia
4,2026-01-08,46.457077,46.888869,46.290246,46.692603,6359264.0,BHP,Australia
...,...,...,...,...,...,...,...,...
20931,2026-06-01,109.330002,113.300003,106.330002,109.430000,134900400.0,Intel,USA
20932,2026-06-02,107.930000,109.000000,104.169998,107.449997,106336200.0,Intel,USA
20933,2026-06-03,112.709999,118.290001,110.860001,116.419998,118928800.0,Intel,USA
20934,2026-06-04,111.779999,113.139999,107.480003,108.400002,77325800.0,Intel,USA
20935,2026-06-05,99.169998,106.480003,98.330002,106.480003,144388800.0,Intel,USA

In [6]:
df.dtypes

Date        object
Close      float64
High       float64
Low        float64
Open       float64
Volume     float64
Company     object
Country     object
dtype: object

In [7]:
df.Date = df.Date.astype('datetime64[ns]')

In [8]:
df

,Date,Close,High,Low,Open,Volume,Company,Country
0,2026-01-02,44.906544,44.906544,44.523818,44.680834,3035952.0,BHP,Australia
1,2026-01-05,45.613117,45.779949,45.053748,45.142070,5888054.0,BHP,Australia
2,2026-01-06,46.339317,46.481613,45.946776,46.437451,8048129.0,BHP,Australia
3,2026-01-07,46.810364,47.585631,46.525772,47.183278,7268819.0,BHP,Australia
4,2026-01-08,46.457077,46.888869,46.290246,46.692603,6359264.0,BHP,Australia
...,...,...,...,...,...,...,...,...
20931,2026-06-01,109.330002,113.300003,106.330002,109.430000,134900400.0,Intel,USA
20932,2026-06-02,107.930000,109.000000,104.169998,107.449997,106336200.0,Intel,USA
20933,2026-06-03,112.709999,118.290001,110.860001,116.419998,118928800.0,Intel,USA
20934,2026-06-04,111.779999,113.139999,107.480003,108.400002,77325800.0,Intel,USA
20935,2026-06-05,99.169998,106.480003,98.330002,106.480003,144388800.0,Intel,USA